# Generated by Django 3.0.6 on 2020-05-21 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=64)),
                ('size', models.CharField(blank=True, choices=[('Small', 'Small'), ('Large', 'Large')], max_length=8)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('baseitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.BaseItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.BaseItem')),
            ],
            options={
                'verbose_name': 'Dinner Platter',
                'verbose_name_plural': 'Dinner Platters',
            },
            bases=('orders.baseitem',),
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.BaseItem')),
            ],
            bases=('orders.baseitem',),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.BaseItem')),
                ('crust', models.CharField(choices=[('Regular', 'Regular'), ('Sicilian', 'Sicilian')], max_length=8)),
                ('max_toppings', models.IntegerField(default=0)),
            ],
            bases=('orders.baseitem',),
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.BaseItem')),
            ],
            bases=('orders.baseitem',),
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.BaseItem')),
            ],
            bases=('orders.baseitem',),
        ),
        migrations.CreateModel(
            name='SubExtra',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.BaseItem')),
            ],
            bases=('orders.baseitem',),
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.BaseItem')),
            ],
            bases=('orders.baseitem',),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderprice', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ordertime', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('message', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('PREPARING', 'Preparing'), ('SHIPPED', 'On Way'), ('DELIVERED', 'Delivered')], default='ORDERED', max_length=16)),
                ('orderitems', models.ManyToManyField(related_name='order', to='orders.IndividualOrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='individualorderitem',
            name='subextra',
            field=models.ManyToManyField(blank=True, related_name='orders_extras', to='orders.SubExtra'),
        ),
        migrations.AddField(
            model_name='individualorderitem',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='orders_toppings', to='orders.Topping'),
        ),
        migrations.CreateModel(
            name='IndividualCartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('baseitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.BaseItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('subextra', models.ManyToManyField(blank=True, related_name='carts_extras', to='orders.SubExtra')),
                ('toppings', models.ManyToManyField(blank=True, related_name='carts_toppings', to='orders.Topping')),
            ],
        ),
    ]
