# Generated by Django 3.0.6 on 2020-05-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=8)),
                ('crust', models.CharField(choices=[('REGULAR', 'Regular'), ('SICILIAN', 'Sicilian')], max_length=8)),
                ('max_toppings', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
