# Generated by Django 3.0.6 on 2020-05-19 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=64)),
                ('size', models.CharField(blank=True, choices=[('Small', 'Small'), ('Large', 'Large')], max_length=8)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.BaseItem')),
            ],
            options={
                'verbose_name': 'Dinner Platter',
                'verbose_name_plural': 'Dinner Platters',
            },
            bases=('orders.baseitem',),
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.BaseItem')),
            ],
            bases=('orders.baseitem',),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.BaseItem')),
                ('crust', models.CharField(choices=[('Regular', 'Regular'), ('Sicilian', 'Sicilian')], max_length=8)),
                ('max_toppings', models.IntegerField(default=0)),
            ],
            bases=('orders.baseitem',),
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.BaseItem')),
            ],
            bases=('orders.baseitem',),
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.BaseItem')),
            ],
            bases=('orders.baseitem',),
        ),
        migrations.CreateModel(
            name='SubExtra',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.BaseItem')),
            ],
            bases=('orders.baseitem',),
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.BaseItem')),
            ],
            bases=('orders.baseitem',),
        ),
    ]
