# Generated by Django 3.0.6 on 2020-05-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('size', models.CharField(blank=True, choices=[('Small', 'Small'), ('Large', 'Large')], max_length=8)),
                ('price', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Dinner Platter',
                'verbose_name_plural': 'Dinner Platters',
            },
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
