# Generated by Django 3.0.6 on 2020-05-20 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualCartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('baseitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.BaseItem')),
                ('subextra', models.ManyToManyField(blank=True, related_name='carts', to='orders.SubExtra')),
                ('toppings', models.ManyToManyField(blank=True, related_name='carts', to='orders.Topping')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
