# Generated by Django 3.0.6 on 2020-05-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Preparing', 'Preparing'), ('On Way', 'On Way'), ('Delivered', 'Delivered')], default='Ordered', max_length=16),
        ),
    ]
