# Generated by Django 3.0.6 on 2020-05-22 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200521_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='ordertime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 14, 37, 39, 495587)),
        ),
    ]
