# Generated by Django 3.0.6 on 2020-05-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200519_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='description',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pasta',
            name='description',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pizza',
            name='description',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='salad',
            name='description',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='sub',
            name='description',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='subextra',
            name='description',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='topping',
            name='description',
            field=models.CharField(default='', max_length=64),
        ),
    ]
